# Generated by Django 4.2.3 on 2025-05-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tedarikci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, verbose_name='Firma Adı')),
                ('hizmet', models.CharField(max_length=255, verbose_name='Verdiği Hizmet')),
                ('yetkili', models.CharField(max_length=255, verbose_name='Firma Yetkilisi')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('adres', models.TextField(blank=True, verbose_name='Adres')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta Adresi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tedarikçi',
                'verbose_name_plural': 'Tedarikçiler',
                'ordering': ['ad'],
            },
        ),
    ]
