# Generated by Django 4.2.3 on 2025-05-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=20, verbose_name='Birim Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Birim',
                'verbose_name_plural': 'Birimler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='KDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(default='', max_length=50, verbose_name='KDV Adı')),
                ('oran', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='KDV Oranı (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KDV',
                'verbose_name_plural': 'KDV Oranları',
                'ordering': ['oran'],
            },
        ),
        migrations.CreateModel(
            name='ParaBirimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=10, verbose_name='Para Birimi Kodu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Para Birimi',
                'verbose_name_plural': 'Para Birimleri',
                'ordering': ['kod'],
            },
        ),
    ]
