# Generated by Django 4.2.3 on 2025-05-12 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametreler', '0001_initial'),
        ('departmanlar', '0001_initial'),
        ('tedarikciler', '0001_initial'),
        ('urunler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatinAlma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('miktar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miktar')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat')),
                ('fis', models.FileField(blank=True, null=True, upload_to='fisler/', verbose_name='Fiş')),
                ('faturaya_baglandi', models.BooleanField(default=False, verbose_name='Faturaya Bağlandı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametreler.birim', verbose_name='Birim')),
                ('departman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departmanlar.departman', verbose_name='Departman')),
                ('kdv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametreler.kdv', verbose_name='KDV')),
                ('para_birimi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parametreler.parabirimi', verbose_name='Para Birimi')),
                ('tedarikci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tedarikciler.tedarikci', verbose_name='Tedarikçi')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunler.urun', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Satın Alma',
                'verbose_name_plural': 'Satın Almalar',
                'ordering': ['-tarih'],
            },
        ),
    ]
