# Generated by Django 4.2.3 on 2025-05-12 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tedarikciler', '0001_initial'),
        ('satin_alma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura_no', models.CharField(max_length=50, verbose_name='Fatura No')),
                ('fatura_tarihi', models.DateField(verbose_name='Fatura Tarihi')),
                ('odeme_tarihi', models.DateField(verbose_name='Ödeme Tarihi')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tutar')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='faturalar/', verbose_name='Fatura Dosyası')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('satin_almalar', models.ManyToManyField(related_name='faturalar', to='satin_alma.satinalma', verbose_name='Satın Almalar')),
                ('tedarikci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tedarikciler.tedarikci', verbose_name='Tedarikçi')),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturalar',
                'ordering': ['-fatura_tarihi'],
            },
        ),
    ]
