# Generated by Django 4.2.3 on 2025-05-12 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tedarikciler', '0001_initial'),
        ('satin_alma', '0001_initial'),
        ('faturalar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='dosya',
        ),
        migrations.RemoveField(
            model_name='fatura',
            name='satin_almalar',
        ),
        migrations.AddField(
            model_name='fatura',
            name='fatura_dosya',
            field=models.FileField(blank=True, null=True, upload_to='faturalar/', verbose_name='Fatura Dosyası'),
        ),
        migrations.AddField(
            model_name='fatura',
            name='satinalmalar',
            field=models.ManyToManyField(blank=True, related_name='faturalari', to='satin_alma.satinalma', verbose_name='Satın Almalar'),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='tedarikci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturalari', to='tedarikciler.tedarikci'),
        ),
    ]
